export enum FlowRoutes {
    HOME = '/',
    REGISTRAION = '/registration',
    LOGIN = '/login',
    DASHBOARD = '/dashboard',
    ADMIN = '/admin',
    USERS = '/admin/users',
    STATUSES = '/admin/statuses',
    NOTIFICATIONS = '/admin/notifications',
    PROFILE = '/profile',
    ACCOUNT = '/account',
    ORDERS = '/orders',
    ADD_ORDERS = '/orders/add',
    CARS = '/cars',
    CUSTOMERS = '/customers',
    SETTINGS = '/settings',
    FORGOT_PASSWORD = '/login/forgot-password',
    TERMS = '/terms',
    CONTACT = '/contact'
}
